views.py
import functools

import flask_login
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from flask_login import login_user, login_required, current_user, logout_user
from werkzeug.security import generate_password_hash
from exts import db
from forms import *
from models import *
from datetime import datetime, timedelta
from sqlalchemy.orm import load_only
import json
from recommend import *

bp = Blueprint('auth', __name__)

@bp.route('/', methods=['GET', 'POST'])
def index():

    if request.method == 'POST':
        keyword = request.form["keyword"]
        #return redirect(url_for('auth.resourceList', key=keyword))

    return render_template('index.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if user.check_password(form.password.data):
                login_user(user, remember=form.remember.data)
                return redirect(url_for('auth.dashboard'))
        flash('Invalid username or password!')

    return render_template('login.html', form=form)


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        if form.validate_username(form.username.data):
            if form.validate_email(form.email.data):
                if form.phoneNumber.data:
                    new_user = User(username=form.username.data, email=form.email.data, _password=hashed_password,
                                    phoneNumber=form.phoneNumber.data)
                else:
                    new_user = User(username=form.username.data, email=form.email.data, _password=hashed_password)
                db.session.add(new_user)
                db.session.commit()
                # hour_for_user = HoursRemain(user_id=new_user.id, hours=10)
                # db.session.add(hour_for_user)
                # db.session.commit()
            else:
                flash(f'Already have same e-mail', 'warning')
                render_template('signup.html', form=form)

        else:
            flash('Already have same username!')
            render_template('signup.html', form=form)

        return redirect(url_for("auth.login"))

    return render_template('signup.html', form=form)


@bp.route('/publish', methods=['GET', 'POST'])
def publish():
    form = PublishForm()
    if flask_login.current_user.is_authenticated:
        if form.validate_on_submit():
            # flash('Publish successful!')
            new_resource = Resource(resource_name=form.resource_name.data, resource_type=form.resource_type.data,
                                    location=form.resource_location.data, description=form.resource_description.data,
                                    provider_id=flask_login.current_user.id)
            db.session.add(new_resource)
            db.session.commit()
            new_likes = Likes(resource_id=new_resource.id, num_likes=0)
            db.session.add(new_likes)
            db.session.commit()

            for hour in form.resource_hours.data:
                new_time = AvailableTimes(resource_id=new_resource.get_id(), times_id=hour)
                db.session.add(new_time)

            for day in form.resource_days.data:
                new_day = AvailableDays(resource_id=new_resource.get_id(), days_id=day)
                db.session.add(new_day)

            db.session.commit()
            db.session.close()

            return redirect(url_for("auth.My_resource"))
    else:
        return redirect(url_for("auth.login"))
    return render_template("publish.html", form=form)



@bp.route('/dashboard')
@login_required
def dashboard():
    hours_remain = User.query.filter_by(id=flask_login.current_user.id).first().hours
    if datetime.now().day == 1:
        hours_remain = 10
        db.session.commit()

    form = DetailForm()
    name = current_user.username
    return render_template('dashboard.html', **locals())


@bp.route('/dashboard/my_resource', methods=['GET', 'POST'])
def My_resource():
    resource_list = Resource.query.filter_by(provider_id=flask_login.current_user.id).all()
    # db.session.query(Resource(provider_id=flask_login.current_user.id))
    if request.method == 'POST':
        r_id = request.get_json()['variable']

        Resource.query.filter_by(id=r_id).delete()
        db.session.commit()
        db.session.close()
    return render_template('my_resource.html', **locals())



@bp.route('/del_order/<variable>', methods=['GET', 'POST'])
def del_resource(variable):
    Order.query.filter_by(id=variable).delete()
    db.session.commit()
    db.session.close()
    return redirect('/dashboard/my_resource')


@bp.route('/edit/<variable>', methods=['GET', 'POST'])
def edit_resource(variable):
    pre_resource = Resource.query.filter_by(id=variable).first()
    form = PublishForm()
    form.resource_name.data = pre_resource.resource_name
    form.resource_location.data = pre_resource.location
    form.resource_type.data = pre_resource.resource_type
    form.resource_description.data = pre_resource.description

    if form.validate_on_submit():
        pre_resource.resource_name = form.resource_name.data
        pre_resource.location = form.resource_location.data
        db.session.commit()
        db.session.close()

    return render_template("publish.html", form=form)


@bp.route('/dashboard/my_order', methods=['GET', 'POST'])
def My_order():
    my_order = Order.query.filter_by(consumer_id=flask_login.current_user.id).all()
    order_at_my_place = Order.query.filter_by(provider_id=flask_login.current_user.id).all()
    today_date = datetime.now()
    my_order_past = []
    my_order_recent = []
    my_order_upcoming = []

    for order in my_order:
        if order.date < today_date:
            my_order_past.append(order)
        elif (order.date - today_date).days <= 3:
            my_order_recent.append(order)
        else:
            my_order_upcoming.append(order)

    if request.method == 'POST':

        dict = request.get_json()
        if 'like' in dict:
            r_id = dict['like']
            likes = Likes.query.filter_by(resource_id=r_id).first()
            likes.num_likes = likes.num_likes + 1

            db.session.add(User_resource_likes(resource_id=r_id, user_id=flask_login.current_user.id))
            db.session.commit()

        if 'cancel' in dict:

            o_id = dict['cancel']
            Order.query.filter_by(order_id=o_id).delete()
            db.session.commit()
            user = User.query.filter_by(id=flask_login.current_user.id).first()
            user.hours = user.hours + 1
            db.session.commit()

    return render_template('myOrders.html', **locals())


@bp.route('/dashboard/wishlist')
def wishlist():
    fav_list = WishList.query.filter_by(user_id=flask_login.current_user.id).all()

    resource_list = []
    for f in fav_list:
        resource_list.append(Resource.query.filter_by(id=f.resource_id).first())

    return render_template('wishlist.html', **locals())


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.index'))


@bp.route('/resourceDetails/<resource_id>', methods=['GET', 'POST'])
def resourceDetails(resource_id):
    r = Resource.query.filter_by(id=resource_id).first()
    p = User.query.filter_by(id=r.provider_id).first()
    num_likes = Likes.query.filter_by(resource_id=r.id).first().num_likes
    if request.method == "POST":
        selected_date = request.form["date"]
        return redirect(url_for("auth.availability", resource_id=resource_id, date=selected_date))
    return render_template('resourceDetails.html', resource=r, provider=p, likes=num_likes)


def is_available(date, resource, startTime, endTime):
    # if endTime < startTime:
    #     return False
    available_day = AvailableDays.query.with_entities(AvailableDays.days_id).filter_by(resource_id=resource.id).all()
    available_time = AvailableTimes.query.with_entities(AvailableTimes.times_id).filter_by(
        resource_id=resource.id).all()

    date_search = datetime.strptime(date, "%Y-%m-%d")
    flag = False
    for day in available_day:
        if date_search.weekday() in day:
            #reserved
            reserved_time = Order.query.filter_by(resource_id=resource.id, date=date_search).with_entities(Order.startTime).all()
            available_time = list(set(available_time) - set(reserved_time))
            for i in range(startTime, endTime):
                if (i,) in available_time:
                    flag = True

    return flag


@bp.route('/resourceList', methods=['GET', 'POST'])
def resourceList():
    resource_list = Resource.query.filter_by().all()
    r_types = list(set(Resource.query.filter_by().with_entities(Resource.resource_type).all()))
    r_locations = list(set(Resource.query.filter_by().with_entities(Resource.location).all()))

    if request.method == 'POST':
        if 'recommend' in request.get_json():

            if flask_login.current_user.is_authenticated:
                user_id = flask_login.current_user.id
                resource_list = recommend(user_id)
            else:
                resource_list = recommend(100)
        if 'search' in request.get_json():
            resource_list = []
            key = request.form["content"]
            location = request.form["Location"]
            type = request.form["Type"]
            date = request.form["date"]
            startTime = request.form["StartTime"]
            endTime = request.form["EndTime"]

            result1 = Resource.query.filter((Resource.resource_name.like("%" + key + "%"))
                                            | (Resource.resource_type.like("%" + key + "%"))

templates/dashboard.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block styles %}
{{super()}}
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/animate.min.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-submenu.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-select.min.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/font-awesome/css/font-awesome.min.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/flaticon/font/flaticon.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/linearicons/style.css')}}">
  <link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/jquery.mCustomScrollbar.css')}}">
  <link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/dropzone.css')}}">
  <link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/slick.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
  <link rel="stylesheet" type="text/css" id="style_sheet" href="{{url_for('static', filename='css/skins/default.css')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
  <link rel="stylesheet" type="text/css" id="style_sheet" href="{{url_for('static', filename='css/skins/default.css')}}">
</head>
<!-- <link rel="stylesheet" href="{{url_for('static', filename='dashboard.css')}}"> -->
{% endblock %}

{% block content %}
<header class="main-header header-2 fixed-header">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand logo pad-0" href="/" style="padding-top: 20px; font-size: 2rem; font-weight: 600;">BOOKIT</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-buttons ml-auto d-none d-xl-block d-lg-block">
            <ul>
              <li><form class="navbar-form navbar-right" style="margin-top: 25px;">
                <input type="text" class="form-control" placeholder="Search...">
              </form></li>
              <li><a class="btn btn-theme btn-md" href="{{ url_for('auth.publish') }}">Publish</a></li>
              <li><a class="btn btn-theme btn-md" style="background-color: white; color: #ff214f !important;" href="{{ url_for('auth.logout') }}">Log Out</a></li>
            </ul>
          </div>
        </div>
    </nav>
  </div>
</header>

<div class="dashboard">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-12 col-sm-12 col-pad">
        <div class="dashboard-nav d-none d-xl-block d-lg-block">
          <div class="dashboard-inner" style="margin-top: 9rem;">
            <ul>
              <li class="nav-item dropdown active"><a href="#">Personal information</a></li>
              <li class="active"><a href="{{ url_for('auth.My_resource') }}" >My resource</a></li>
              <li class="active"><a href="{{ url_for('auth.My_order') }}" >My Order</a></li>
              <li class="active"><a href="{{ url_for('auth.wishlist') }}">Wishlist</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12 col-pad">
        <div class="content-area5" style="margin-top: 10rem;">
          <div class="dashboard-content">
            <div class="dashboard-header clearfix">
              <div class="row col-sm-12 col-md-6"><h4>Welcome, {{ name }}</h4></div>
            </div>
            <div class="dashboard-list">
              <h3 class="heading">Personal information</h3>
              <div class="dashboard-message contact-2 bdr clearfix">
                <p style="font-size:12pt;"> You have <b>{{ hours_remain }}</b> hours remaining for this month.</p>
                <div class="col-lg-6 col-md-6">
                  <div class="form-group email">
                    <label class="control-label">Gender</label>
                    <select class="form-select" id="gender_edit" name="gender" style="height: 40px;">
                      <option value="male">male</option>
                      <option value="female">female</option>
                      <option value="other">other</option>
                    </select>
                  </div>
                </div>

                <div class="col-lg-6 col-md-6">
                  <div class="form-group email">
                    <label class="control-label">Birthday</label>
                    <input class="form-control" id="birthday_edit" name="birthday" type="date" style="line-height: 20px;">
                  </div>
                </div>

                <div class="col-lg-6 col-md-6">
                  <div class="form-group email">
                    <label class="control-label">First name</label>
                    <input class="form-control" id="fname_edit" name="birthday" type="text" >
                  </div>
                </div>

                <div class="col-lg-6 col-md-6">
                  <div class="form-group email">
                    <label class="control-label">Last name</label>
                    <input class="form-control" id="lname_edit" name="birthday" type="text" >
                  </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12">
                  <div class="form-group message">
                    <label>Describe yourself briefly</label>
                    <textarea class="form-control" name="message" placeholder="Personal info" >{{personal_description}}</textarea>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="send-btn">
                    <button type="submit" class="btn btn-md button-theme" nclick="submit_info()" id="submit_button">Save information</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function submit_info(){
    location.reload(true);
  }
</script>
<script src="{{url_for('static', filename='js/bootstrap-select.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery-2.2.0.min.js')}}"></script>
<script src="{{url_for('static', filename='js/popper.min.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap-submenu.js')}}"></script>
<script src="{{url_for('static', filename='js/rangeslider.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.mb.YTPlayer.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.easing.1.3.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.scrollUp.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js')}}"></script>
<script src="{{url_for('static', filename='js/slick.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.filterizr.js')}}"></script>

<script src="{{url_for('static', filename='js/jquery.countdown.js')}}"></script>



{% endblock %}

templates/login.html
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='signin.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/style.css') }}"/>
{% endblock %}

{% block content %}
    <header class="header">
	    <nav class="navbar fixed-top">
            <a class="logo-link" href="index.html">

		    </a>
		    <div class="navbar__menu">
		        <button class="hamburger" type="button">
				    <span></span>
					<span></span>
				</button>
			    <ul class="nav">
				    <li class="nav__item"><a class="nav__link" href="{{ url_for('auth.index') }}"><span data-hover="Home">Home</span></a></li>
				    <li class="nav__item"><a class="nav__link" href="{{ url_for('auth.resourceList') }}"><span data-hover="Resource">Resources</span></a></li>
				    <li class="nav__item"><a class="nav__link" href="{{ url_for('auth.publish') }}"><span data-hover="Publish">Publish</span></a></li>
                    <li class="nav__item"><a class="nav__link" href="blog.html"><span data-hover="Blog"></span></a></li>

			    </ul>
	        </div>
		    <div class="navbar__btn">

		    </div>
	    </nav>
	</header>
    <main class="main">
        <section class="container section section-first">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
           <form class="form-signin" method="POST" action="/login">
            <h2 class="form-signin-heading">Please sign in</h2>

            {{ form.hidden_tag() }}
            {{ wtf.form_field(form.username) }}
            {{ wtf.form_field(form.password) }}
            {{ wtf.form_field(form.remember) }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <a href="{{ url_for('auth.signup') }}">Switch to register</a>
          </form>

        </section>
    </main>
{% endblock %}

templates/my_resource.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Dashboard
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/animate.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-submenu.css')}}">

<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-select.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/font-awesome/css/font-awesome.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/flaticon/font/flaticon.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/linearicons/style.css')}}">
<link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/jquery.mCustomScrollbar.css')}}">
<link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/dropzone.css')}}">
<link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/slick.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" id="style_sheet" href="{{url_for('static', filename='css/skins/default.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" id="style_sheet" href="{{url_for('static', filename='css/skins/default.css')}}">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}

{% block content %}
<header class="main-header header-2 fixed-header">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand logo pad-0" href="/" style="padding-top: 20px; font-size: 2rem; font-weight: 600;">BOOKIT</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-buttons ml-auto d-none d-xl-block d-lg-block">
            <ul>
              <li><form class="navbar-form navbar-right" style="margin-top: 25px;">
                <input type="text" class="form-control" placeholder="Search...">
              </form></li>
              <li><a class="btn btn-theme btn-md" href="{{ url_for('auth.publish') }}">Publish</a></li>
              <li><a class="btn btn-theme btn-md" style="background-color: white; color: #ff214f !important;" href="{{ url_for('auth.logout') }}">Log Out</a></li>
            </ul>
          </div>
        </div>
    </nav>
  </div>
</header>
<div class="dashboard">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-12 col-sm-12 col-pad">
        <div class="dashboard-nav d-none d-xl-block d-lg-block" style="height: 94.8vh;">
          <div class="dashboard-inner" style="margin-top: 9rem;">
            <ul>
              <li class="nav-item dropdown active"><a href="{{ url_for('auth.dashboard') }}">Personal information</a></li>
              <li class="active"><a href="{{ url_for('auth.My_resource') }}" >My resources</a></li>
              <li class="active"><a href="{{ url_for('auth.My_order') }}" >My Orders</a></li>
              <li class="active"><a href="{{ url_for('auth.wishlist') }}">Wishlist</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12 col-pad">
        <div class="content-area5">
          <div class="dashboard-content" style="margin-top: 10rem;">
            <div class="dashboard-header clearfix">
              <div class="row">
                <div class="col-sm-12 col-md-6"><h4>Resources</h4></div>
              </div>
            </div>
            <div class="dashboard-list">
              <table class="manage-table">
                <tbody>
                {% for resource in resource_list %}
                  <tr class="responsive-table" id="res{{ resource.id }}">
                    <td class="listing-photoo">
                      <img src="{{url_for('static', filename='restraunt_1.jpg')}}" alt="image of the resource" class="img-fluid">
                    </td>
                    <td class="title-container">
                        <h2><a href="{{ url_for('auth.resourceDetails', resource_id=resource.id) }}">{{resource.resource_name}}</a></h2>
                        <h5 class="d-none d-xl-block d-lg-block d-md-block"><i class="flaticon-pin"></i> {{resource.location}} </h5>
                        <h6 class="table-property-price">{{resource.description}}</h6>
                    </td>
                    <td class="expire-date"> </td>
                    <td class="action">
                        <a href="{{ url_for('auth.edit_resource', variable=resource.id) }}"><i class="fa fa-pencil"></i> Edit</a>
                        <a onclick="deleteItem({{ resource.id }})" class="delete"><i class="fa fa-remove"></i> Delete</a>
                    </td>
                  </tr>
                {%endfor%}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <!-- Script to remove HTML element -->
<script>
  const deleteItem = rid => {
    const el = document.getElementById('res' + rid)
    Swal.fire({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
      if (result.isConfirmed) {
        $.ajax({
          url: "{{ url_for('auth.My_resource') }}",
          data: JSON.stringify({"variable": rid}),
          type: "POST",
          dataType: "html",
          contentType: "application/json",
        })
        .done(function(data) {
          el.remove()
          Swal.fire('Success', 'The resource has been deleted', 'success')
        })
        .fail(function() {
          Swal.fire('Error', 'Failed to delete', 'error')
        })
      }
    })
    
  }
</script>

{% endblock %}

templates/search.html
<form method="post">
    {{ form.key }}
    {{ form.csrf_token }}
    {{ form.submit }}
</form>

templates/wishlist.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Dashboard
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/animate.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-submenu.css')}}">

<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-select.min.css')}}">

<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/font-awesome/css/font-awesome.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/flaticon/font/flaticon.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='fonts/linearicons/style.css')}}">
<link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/jquery.mCustomScrollbar.css')}}">
<link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/dropzone.css')}}">
<link rel="stylesheet" type="text/css"  href="{{url_for('static', filename='css/slick.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" id="style_sheet" href="{{url_for('static', filename='css/skins/default.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" id="style_sheet" href="{{url_for('static', filename='css/skins/default.css')}}">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}

{% block content %}
<header class="main-header header-2 fixed-header">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand logo pad-0" href="/" style="padding-top: 20px; font-size: 2rem; font-weight: 600;">BOOKIT</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-buttons ml-auto d-none d-xl-block d-lg-block">
            <ul>
              <li><form class="navbar-form navbar-right" style="margin-top: 25px;">
                <input type="text" class="form-control" placeholder="Search...">
              </form></li>
              <li><a class="btn btn-theme btn-md" href="{{ url_for('auth.publish') }}">Publish</a></li>
              <li><a class="btn btn-theme btn-md" style="background-color: white; color: #ff214f !important;" href="{{ url_for('auth.logout') }}">Log Out</a></li>
            </ul>
          </div>
        </div>
    </nav>
  </div>
</header>
<div class="dashboard">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-12 col-sm-12 col-pad">
        <div class="dashboard-nav d-none d-xl-block d-lg-block" style="height: 94.8vh;">
          <div class="dashboard-inner" style="margin-top: 9rem;">
            <ul>
              <li class="nav-item dropdown active"><a href="{{ url_for('auth.dashboard') }}">Personal information</a></li>
              <li class="active"><a href="{{ url_for('auth.My_resource') }}" >My resources</a></li>
              <li class="active"><a href="{{ url_for('auth.My_order') }}" >My Orders</a></li>
              <li class="active"><a href="{{ url_for('auth.wishlist') }}">Wishlist</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12 col-pad">
        <div class="content-area5">
          <div class="dashboard-content" style="margin-top: 10rem;">
            <div class="dashboard-header clearfix">
              <div class="row">
                <div class="col-sm-12 col-md-6"><h4>Resources</h4></div>
              </div>
            </div>
            <div class="dashboard-list">
              <table class="manage-table">
                <tbody>
                {% for resource in resource_list %}
                  <tr class="responsive-table" id="res{{ resource.id }}">
                    <td class="listing-photoo">
                      <img src="{{url_for('static', filename='restraunt_1.jpg')}}" alt="image of the resource" class="img-fluid">
                    </td>
                    <td class="title-container">
                        <h2><a href="{{ url_for('auth.resourceDetails', resource_id=resource.id) }}">{{resource.resource_name}}</a></h2>
                        <h5 class="d-none d-xl-block d-lg-block d-md-block"><i class="flaticon-pin"></i> {{resource.location}} </h5>
                        <h6 class="table-property-price">{{resource.description}}</h6>
                    </td>
                  </tr>
                {%endfor%}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}